Repository recordrobotics/2022_Rewrite, pull requests merged in 2022-06, with the labels that each got.

#33 Auto Flywheel
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoShoot.java
Labels: enhancement, works

#32 Auto Acquisition
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoDeployAcq.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoSpinAcq.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualAcquisition.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Acquisition.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Sensors.java
Labels: enhancement, testing

#42 rescheduling fix
  src/main/java/org/recordrobotics/munchkin/RobotContainer.java
  src/main/java/org/recordrobotics/munchkin/util/Pair.java
Labels: testing
