Repository recordrobotics/2022_Rewrite, pull requests merged in 2022-05, with the labels that each got.

#20 created Rotator and ManualRotator, set RobotMap ports
  src/main/java/org/recordrobotics/munchkin/RobotMap.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualRotator.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Rotator.java
Labels: enhancement

#22 Cleanup
  build.gradle
  pmd.xml
  src/main/java/org/recordrobotics/munchkin/Main.java
  src/main/java/org/recordrobotics/munchkin/Robot.java
  src/main/java/org/recordrobotics/munchkin/RobotContainer.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualAcquisition.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualClimbers.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualFlywheel.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualRotator.java
Labels: enhancement, works

#25 Sensors
  src/main/java/org/recordrobotics/munchkin/Constants.java
  src/main/java/org/recordrobotics/munchkin/RobotMap.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Flywheel.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Sensors.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Subsystems.java
Labels: enhancement

#27 Manual Command Error Checking
  src/main/java/org/recordrobotics/munchkin/commands/ExampleCommand.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualAcquisition.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualClimbers.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualFlywheel.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualRotator.java
  src/main/java/org/recordrobotics/munchkin/subsystems/ExampleSubsystem.java
Labels: enhancement

#34 Subsystems Complete
  .vscode/launch.json
  build.gradle
  pmd.xml
  src/main/java/org/recordrobotics/munchkin/Constants.java
  src/main/java/org/recordrobotics/munchkin/Main.java
  src/main/java/org/recordrobotics/munchkin/Robot.java
  src/main/java/org/recordrobotics/munchkin/RobotContainer.java
  src/main/java/org/recordrobotics/munchkin/RobotMap.java
  src/main/java/org/recordrobotics/munchkin/commands/ExampleCommand.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualAcquisition.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualClimbers.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualFlywheel.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualRotator.java
  src/main/java/org/recordrobotics/munchkin/control/DoubleControl.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Acquisition.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Climbers.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
  src/main/java/org/recordrobotics/munchkin/subsystems/ExampleSubsystem.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Flywheel.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Rotator.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Sensors.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Subsystems.java
  vendordeps/Phoenix.json
  vendordeps/REVLib.json
  vendordeps/WPILibNewCommands.json
  vendordeps/navx_frc.json
Labels: works

#35 Dashboard
  src/main/java/org/recordrobotics/munchkin/Constants.java
  src/main/java/org/recordrobotics/munchkin/RobotContainer.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Climbers.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Rotator.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Sensors.java
Labels: enhancement, works

#36 Climber & Rotator Auto Commands
  src/main/java/org/recordrobotics/munchkin/Constants.java
  src/main/java/org/recordrobotics/munchkin/Robot.java
  src/main/java/org/recordrobotics/munchkin/RobotContainer.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoClimbTo.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoPullUp.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoResetRotator.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/AutoRotateTo.java
  src/main/java/org/recordrobotics/munchkin/commands/auto/Direction.java
  src/main/java/org/recordrobotics/munchkin/commands/dashboard/DashResetClimbEncoder.java
  src/main/java/org/recordrobotics/munchkin/commands/dashboard/DashRunProcedure.java
  src/main/java/org/recordrobotics/munchkin/commands/group/SeqLiftHigh.java
  src/main/java/org/recordrobotics/munchkin/commands/group/SeqLiftMid.java
  src/main/java/org/recordrobotics/munchkin/commands/group/SeqLiftNext.java
  src/main/java/org/recordrobotics/munchkin/commands/group/SeqLiftTrav.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualAcquisition.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualClimbers.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualFlywheel.java
  src/main/java/org/recordrobotics/munchkin/commands/manual/ManualRotator.java
  src/main/java/org/recordrobotics/munchkin/control/DoubleControl.java
  src/main/java/org/recordrobotics/munchkin/control/LegacyControl.java
  src/main/java/org/recordrobotics/munchkin/subsystems/Rotator.java
  src/main/java/org/recordrobotics/munchkin/util/Procedure.java
Labels: enhancement, works
